export const autoCommentConfigurationDefaults = {
  scrollDuration: 5,
  commentDelay: 5,
  maxPosts: 5,
  duplicateWindow: 24,
  finishListModeEnabled: false,
  commentAsCompanyEnabled: false,
  timeFilterEnabled: false,
  minPostAge: 1,
  manualApproveEnabled: false,
  authenticityBoostEnabled: false,
  defaultCommentStyle: "PROFESSIONAL" as const,
  targetListId: undefined,
  commentStyleId: undefined,
  commentProfileName: "",
  languageAwareEnabled: false,
  skipCompanyPagesEnabled: false,
  blacklistEnabled: false,
  skipPromotedPostsEnabled: false,
  skipFriendActivitiesEnabled: false,
  targetListEnabled: false,
};
