import { GoogleGenAI } from "@google/genai";
import { TRPCError } from "@trpc/server";

import type { CommentGenerationOutput } from "../schema-validators";
import {
  commentGenerationInputSchema,
  commentGenerationOutputSchema,
} from "../schema-validators";
import { createTRPCRouter, protectedProcedure } from "../trpc";

// Instantiate at module load like Stripe/Apify routers
// Use fallback empty string to avoid throwing during Next.js build time
// The service will only be used at runtime when mutations are called
const apiKey = process.env.GOOGLE_GENAI_API_KEY ?? "";
const ai = new GoogleGenAI({ apiKey });

/**
 * Sanitise AI-generated comment by stripping common AI artefacts:
 * - Leading/trailing quotation marks
 * - Place-holders wrapped in [], {}, <> (e.g. [Author's Name])
 * - Back-ticks and markdown bold / italic markers (** __ * _)
 * - Parenthetical placeholders containing keywords like Author, Company, Name, insert, placeholder
 *
 * The goal is to leave a natural-looking comment while never stripping legitimate
 * human text beyond these obvious artefacts.
 */
const sanitizeGeneratedComment = (raw: string): string => {
  if (!raw) return "";
  let result = raw.trim();

  // 1. Remove leading/trailing quotes (straight or curly)
  result = result.replace(/^(["'“”‘’]+)/, "").replace(/(["'“”‘’]+)$/, "");

  // 2. Remove wrapping backticks (single or triple) and any isolated backticks
  result = result
    .replace(/^`{1,3}/, "")
    .replace(/`{1,3}$/, "")
    .replace(/`+/g, "");

  // 3. Remove markdown bold/italic markers
  result = result.replace(/\*\*|__|\*|_/g, "");

  // 4. Remove anything inside square, curly, or angle brackets – typically AI placeholders
  result = result
    .replace(/\[[^\]]*?\]/g, "")
    .replace(/\{[^}]*?\}/g, "")
    .replace(/<[^>]*?>/g, "");

  // 5. Remove parenthetical placeholders containing specific keywords
  result = result.replace(
    /\(([^)]*(author|company|name|insert|placeholder)[^)]*)\)/gi,
    "",
  );

  // 6. Replace em-dashes and en-dashes with normal dashes, removing whitespace
  result = result.replace(/\s*[—–]\s*/g, "-");

  // Collapse multiple spaces and trim again
  result = result.replace(/\s{2,}/g, " ").trim();

  return result;
};

/**
 * AI Comments Router
 *
 * Handles AI-powered comment generation using Google GenAI
 * Requires authentication via Clerk protectedProcedure
 */

export const aiCommentsRouter = createTRPCRouter({
  /**
   * Generate AI comment based on post content and style guide
   * Protected procedure requiring user authentication
   *
   * Note: Rate limiting (daily comment limit) is handled separately
   * via getDailyLimit and incrementDailyLimit endpoints
   */
  generateComment: protectedProcedure
    .input(commentGenerationInputSchema)
    .output(commentGenerationOutputSchema)
    .mutation(async ({ input }): Promise<CommentGenerationOutput> => {
      const { postContent, styleGuide, adjacentComments } = input;

      console.log(
        "AI Comments Router: Starting comment generation for content length:",
        postContent.length || 0,
      );

      const existingComments = JSON.stringify(adjacentComments);

      const systemPrompt = `
You are a LinkedIn influencer commenting on a post. 

Generate concise, engaging, thoughtful comment for a single LinkedIn post below

---begin post content---
${postContent}
---end post content---

Importantly, ahere strictly to the following additional rules:

- ONLY REPSOND WITH THE COMMENT. DO NOT REPLY WITH ANYTHING ELSE LIKE QUOTATIONS OR ANYTHING ELSE.
- Keep comments professional yet conversational
- avoid generic responses.
- do not return any artefacts that might imply that the comment was generated by AI like placeholders [First's Name] or [Post Content].
- Your final output must be only the raw text of the comment, ready to be copied and pasted.
- Under **NO CIRCUMSTANCES** should your response contain any placeholders, brackets, or meta-text. These are forbidden AI artifacts.
- Do NOT use asterisks, quotation marks, backticks, dashes, or any markdown formatting markers.
- Never begin with phrases like "I'm curious".
- No filler phrases (great post, this resonates, amazing insight, etc.).
- Do not use filler phrases like great post, great insights, this hit hard, love this, thanks for sharing.
- Can sometimes add a single emoji to emphasize a point or emotion (powerful, insightful, motivating)


FORBIDDEN ARTIFACTS INCLUDE:

[Author's Name]
[insert specific detail here]
[Company Name]

Quotation marks around concepts you are referencing (e.g., the "trust" issue)
Any text inside [...] or {...}

Remember, your generated response will be posted directly with no processing, so it MUST NOT contain any redundant text like “here is the comment” or quotes or syntaxs of the like that might raise suspicion that this was ak generated.

ADDITIONAL GLOBAL STYLE REQUIREMENTS:


Important Authentic Reference: 
- You must read carefully other comments in the post and micmic them entirely in language and content direction. You can still refer to the user's guide below to customize the comment, BUT the language, style, format, structure, tone, etc must mimic as close as possible to the existing comments. If there are multiple existing comments present, choose the most HUMAN and AUTHENTIC comment to mimic. It doesn't matter if the existing comment is short or long, even one or 2 words is acceptable but you must mimic their content, lanugage, pronouns, etc. If the existing comment is in a different language, YOU MUST write your comment in that lanugage mimicking the style of those comments as well. But be cafeful, you must not copy entirely from the existing comment. Only mimic the tone and style, but you must have a different wording or perspective - taking refernece from the user's style guide below. 

Again, DO NOT COPY ENTIRELY FROM THE EXISTING COMMENT. ONLY MIMIC THE TONE AND STYLE, BUT YOU MUST HAVE A DIFFERENT WORDING OR PERSPECTIVE - TAKING REFERNECE FROM THE USER'S STYLE GUIDE BELOW.

Here are the existing comment(s) as a JSON array OR a string message when unavailable (each object has commentContent, likeCount, replyCount):

---begin existing comments---
${existingComments}
---end existing comments---

if there are no existing comments, you must mimic the style and tone of the user's style guide below.

Lastly but most importantly, you must ahere to the style guide below given by the user, this is guide from the user and they are more important the the system guide above, so if there are any conflicts, you must follow the user's guide below first and then the system guide above: 

---begin style guide---
${styleGuide}
---end style guide---
`;

      console.log("Final prompt fed into the ai:", systemPrompt);

      // Validate API key at runtime when actually using the service
      if (!apiKey) {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message:
            "AI service configuration error: GOOGLE_GENAI_API_KEY not found",
        });
      }

      try {
        const response = await ai.models.generateContent({
          model: "gemini-2.5-flash-lite",
          contents: systemPrompt,
          config: {
            // Lower temperature = faster sampling, still creative enough
            temperature: 0.8,
            // Limit output tokens for shorter comments
            maxOutputTokens: 150,
          },
        });

        const generatedComment =
          response.text ?? "Great post! Thanks for sharing.";
        const isFallback = !response.text;

        // Sanitize the comment to remove any residual AI artefacts.
        // If sanitisation results in an empty string, fall back to a safe generic comment.
        const cleanComment = sanitizeGeneratedComment(generatedComment);
        const finalComment =
          cleanComment.length > 0
            ? cleanComment
            : "Great post! Thanks for sharing.";

        console.log(
          "AI Comments Router: Successfully generated comment:",
          finalComment.substring(0, 100) + "...",
        );

        return {
          comment: finalComment,
          success: true,
          // Mark as fallback if the AI failed or if sanitisation stripped everything
          fallback: isFallback || cleanComment.length === 0,
        };
      } catch (error) {
        console.error("AI Comments Router: Error generating comment:", error);
        // Return fallback comment instead of throwing error
        return {
          comment: "Great post! Thanks for sharing.",
          success: false,
          fallback: true,
          error: error instanceof Error ? error.message : String(error),
        };
      }
    }),
});
