import { GoogleGenAI } from "@google/genai";
import { TRPCError } from "@trpc/server";

import type { CommentGenerationOutput } from "../schema-validators";
import {
  commentGenerationInputSchema,
  commentGenerationOutputSchema,
} from "../schema-validators";
import { createTRPCRouter, protectedProcedure } from "../trpc";

/**
 * AI Comments Router
 *
 * Handles AI-powered comment generation using Google GenAI
 * Requires authentication via Clerk protectedProcedure
 */

export const aiCommentsRouter = createTRPCRouter({
  /**
   * Generate AI comment based on post content and style guide
   * Protected procedure requiring user authentication
   */
  generateComment: protectedProcedure
    .input(commentGenerationInputSchema)
    .output(commentGenerationOutputSchema)
    .mutation(async ({ input }): Promise<CommentGenerationOutput> => {
      const { postContent, styleGuide } = input;

      console.log(
        "AI Comments Router: Starting comment generation for content length:",
        postContent?.length || 0,
      );

      // Get Google GenAI API key from environment
      const apiKey = process.env.GOOGLE_GENAI_API_KEY;
      if (!apiKey) {
        console.error(
          "AI Comments Router: GOOGLE_GENAI_API_KEY not found in environment",
        );
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "AI service configuration error",
        });
      }

      const ai = new GoogleGenAI({ apiKey });

      const systemPrompt = `
You are a LinkedIn influencer commenting on a post. 

Generate concise but engaging comments for a single LinkedIn. 

Super Importantly, ONLY REPSOND WITH THE COMMENT. DO NOT REPLY WITH ANYTHING ELSE LIKE QUOTATIONS OR ANYTHING ELSE.

You must ahere to the style guide: ${styleGuide}. 

Importantly, ahere strictly to the following additional rules:
- Keep comments professional yet conversational
- under 100 words
- avoid generic responses.

Super Importantly, ONLY REPSOND WITH THE COMMENT. DO NOT REPLY WITH ANYTHING ELSE LIKE QUOTATIONS OR ANYTHING ELSE.

Generate a thoughtful comment for this LinkedIn post: ${postContent}

Super Importantly, ONLY REPSOND WITH THE COMMENT. DO NOT REPLY WITH ANYTHING ELSE LIKE QUOTATIONS OR ANYTHING ELSE.

Super Importantly, do not return any artefacts that might imply that the comment was generated by AI like placeholders [First's Name] or [Post Content].

The postContent above likely starts with the author's name. Address the author's name somewhere in your comment. If you can't find a name, don't try to put in placeholder, just don't address them.

It's important that you think very hard to make sure that what you return is as natural and human sounding/looking as possible without raising any red flags.
`;

      try {
        const response = await ai.models.generateContent({
          model: "gemini-2.0-flash-lite",
          contents: systemPrompt,
          config: {
            maxOutputTokens: 100,
            temperature: 0.7,
          },
        });

        const generatedComment =
          response.text || "Great post! Thanks for sharing.";
        const isFallback = !response.text;

        console.log(
          "AI Comments Router: Successfully generated comment:",
          generatedComment.substring(0, 100) + "...",
        );

        return {
          comment: generatedComment,
          success: true,
          fallback: isFallback,
        };
      } catch (error) {
        console.error("AI Comments Router: Error generating comment:", error);

        // Log detailed error information
        const errorDetails = {
          message: error instanceof Error ? error.message : String(error),
          stack: error instanceof Error ? error.stack : undefined,
          name: error instanceof Error ? error.name : "Unknown",
          postContentLength: postContent ? postContent.length : 0,
          timestamp: new Date().toISOString(),
          type: "google_genai_error",
        };

        console.error("AI Comments Router: Error details:", errorDetails);

        // Return fallback comment instead of throwing error
        return {
          comment: "Great post! Thanks for sharing.",
          success: false,
          fallback: true,
          error: error instanceof Error ? error.message : String(error),
        };
      }
    }),
});
