import { type DropdownItem } from "./nav-dropdown-container";

// Mock data for dropdowns
export const freeToolsData: DropdownItem[] = [
  {
    id: "tool-1",
    title: "Tool 1",
    href: "#",
    iconEmoji: "🔧",
    description: "Description for tool 1",
    previewImage: "https://via.placeholder.com/600x400?text=Tool+1",
  },
  {
    id: "tool-2",
    title: "Tool 2",
    href: "#",
    iconEmoji: "✨",
    description: "Description for tool 2",
    previewImage: "https://via.placeholder.com/600x400?text=Tool+2",
  },
  {
    id: "tool-3",
    title: "Tool 3",
    href: "#",
    iconEmoji: "⚡",
    description: "Description for tool 3",
    previewImage: "https://via.placeholder.com/600x400?text=Tool+3",
  },
  {
    id: "tool-4",
    title: "Tool 4",
    href: "#",
    iconEmoji: "🎯",
    description: "Description for tool 4",
    previewImage: "https://via.placeholder.com/600x400?text=Tool+4",
  },
  {
    id: "tool-5",
    title: "Tool 5",
    href: "#",
    iconEmoji: "📈",
    description: "Description for tool 5",
    previewImage: "https://via.placeholder.com/600x400?text=Tool+5",
  },
  {
    id: "tool-6",
    title: "Tool 6",
    href: "#",
    iconEmoji: "👥",
    description: "Description for tool 6",
    previewImage: "https://via.placeholder.com/600x400?text=Tool+6",
  },
  {
    id: "tool-7",
    title: "Tool 7",
    href: "#",
    iconEmoji: "📊",
    description: "Description for tool 7",
    previewImage: "https://via.placeholder.com/600x400?text=Tool+7",
  },
  {
    id: "tool-8",
    title: "Tool 8",
    href: "#",
    iconEmoji: "💡",
    description: "Description for tool 8",
    previewImage: "https://via.placeholder.com/600x400?text=Tool+8",
  },
];

export const growthDirectoriesData: DropdownItem[] = [
  {
    id: "dir-1",
    title: "Directory 1",
    href: "#",
    iconEmoji: "📁",
    description: "Category description 1",
    previewImage: "https://via.placeholder.com/600x400?text=Directory+1",
  },
  {
    id: "dir-2",
    title: "Directory 2",
    href: "#",
    iconEmoji: "📁",
    description: "Category description 2",
    previewImage: "https://via.placeholder.com/600x400?text=Directory+2",
  },
  {
    id: "dir-3",
    title: "Directory 3",
    href: "#",
    iconEmoji: "📁",
    description: "Category description 3",
    previewImage: "https://via.placeholder.com/600x400?text=Directory+3",
  },
  {
    id: "dir-4",
    title: "Directory 4",
    href: "#",
    iconEmoji: "📁",
    description: "Category description 4",
    previewImage: "https://via.placeholder.com/600x400?text=Directory+4",
  },
  {
    id: "dir-5",
    title: "Directory 5",
    href: "#",
    iconEmoji: "📁",
    description: "Category description 5",
    previewImage: "https://via.placeholder.com/600x400?text=Directory+5",
  },
  {
    id: "dir-6",
    title: "Directory 6",
    href: "#",
    iconEmoji: "📁",
    description: "Category description 6",
    previewImage: "https://via.placeholder.com/600x400?text=Directory+6",
  },
  {
    id: "dir-7",
    title: "Directory 7",
    href: "#",
    iconEmoji: "📁",
    description: "Category description 7",
    previewImage: "https://via.placeholder.com/600x400?text=Directory+7",
  },
  {
    id: "dir-8",
    title: "Directory 8",
    href: "#",
    iconEmoji: "📁",
    description: "Category description 8",
    previewImage: "https://via.placeholder.com/600x400?text=Directory+8",
  },
];

export const caseStudiesData: DropdownItem[] = [
  {
    id: "case-1",
    title: "Case Study 1",
    href: "#",
    iconEmoji: "💼",
    description: "Client success story 1",
    previewImage: "https://via.placeholder.com/600x400?text=Case+Study+1",
  },
  {
    id: "case-2",
    title: "Case Study 2",
    href: "#",
    iconEmoji: "💼",
    description: "Client success story 2",
    previewImage: "https://via.placeholder.com/600x400?text=Case+Study+2",
  },
  {
    id: "case-3",
    title: "Case Study 3",
    href: "#",
    iconEmoji: "💼",
    description: "Client success story 3",
    previewImage: "https://via.placeholder.com/600x400?text=Case+Study+3",
  },
  {
    id: "case-4",
    title: "Case Study 4",
    href: "#",
    iconEmoji: "💼",
    description: "Client success story 4",
    previewImage: "https://via.placeholder.com/600x400?text=Case+Study+4",
  },
  {
    id: "case-5",
    title: "Case Study 5",
    href: "#",
    iconEmoji: "💼",
    description: "Client success story 5",
    previewImage: "https://via.placeholder.com/600x400?text=Case+Study+5",
  },
  {
    id: "case-6",
    title: "Case Study 6",
    href: "#",
    iconEmoji: "💼",
    description: "Client success story 6",
    previewImage: "https://via.placeholder.com/600x400?text=Case+Study+6",
  },
  {
    id: "case-7",
    title: "Case Study 7",
    href: "#",
    iconEmoji: "💼",
    description: "Client success story 7",
    previewImage: "https://via.placeholder.com/600x400?text=Case+Study+7",
  },
  {
    id: "case-8",
    title: "Case Study 8",
    href: "#",
    iconEmoji: "💼",
    description: "Client success story 8",
    previewImage: "https://via.placeholder.com/600x400?text=Case+Study+8",
  },
];

export const expertGuideData: DropdownItem[] = [
  {
    id: "guide-1",
    title: "Guide 1",
    href: "#",
    iconEmoji: "🎓",
    description: "Expert guide topic 1",
    previewImage: "https://via.placeholder.com/600x400?text=Guide+1",
  },
  {
    id: "guide-2",
    title: "Guide 2",
    href: "#",
    iconEmoji: "🎓",
    description: "Expert guide topic 2",
    previewImage: "https://via.placeholder.com/600x400?text=Guide+2",
  },
  {
    id: "guide-3",
    title: "Guide 3",
    href: "#",
    iconEmoji: "🎓",
    description: "Expert guide topic 3",
    previewImage: "https://via.placeholder.com/600x400?text=Guide+3",
  },
  {
    id: "guide-4",
    title: "Guide 4",
    href: "#",
    iconEmoji: "🎓",
    description: "Expert guide topic 4",
    previewImage: "https://via.placeholder.com/600x400?text=Guide+4",
  },
  {
    id: "guide-5",
    title: "Guide 5",
    href: "#",
    iconEmoji: "🎓",
    description: "Expert guide topic 5",
    previewImage: "https://via.placeholder.com/600x400?text=Guide+5",
  },
  {
    id: "guide-6",
    title: "Guide 6",
    href: "#",
    iconEmoji: "🎓",
    description: "Expert guide topic 6",
    previewImage: "https://via.placeholder.com/600x400?text=Guide+6",
  },
  {
    id: "guide-7",
    title: "Guide 7",
    href: "#",
    iconEmoji: "🎓",
    description: "Expert guide topic 7",
    previewImage: "https://via.placeholder.com/600x400?text=Guide+7",
  },
  {
    id: "guide-8",
    title: "Guide 8",
    href: "#",
    iconEmoji: "🎓",
    description: "Expert guide topic 8",
    previewImage: "https://via.placeholder.com/600x400?text=Guide+8",
  },
];

export const alternativesData: DropdownItem[] = [
  {
    id: "alt-1",
    title: "Alternative 1",
    href: "#",
    iconEmoji: "🔀",
    description: "Alternative solution 1",
    previewImage: "https://via.placeholder.com/600x400?text=Alternative+1",
  },
  {
    id: "alt-2",
    title: "Alternative 2",
    href: "#",
    iconEmoji: "🔀",
    description: "Alternative solution 2",
    previewImage: "https://via.placeholder.com/600x400?text=Alternative+2",
  },
  {
    id: "alt-3",
    title: "Alternative 3",
    href: "#",
    iconEmoji: "🔀",
    description: "Alternative solution 3",
    previewImage: "https://via.placeholder.com/600x400?text=Alternative+3",
  },
  {
    id: "alt-4",
    title: "Alternative 4",
    href: "#",
    iconEmoji: "🔀",
    description: "Alternative solution 4",
    previewImage: "https://via.placeholder.com/600x400?text=Alternative+4",
  },
  {
    id: "alt-5",
    title: "Alternative 5",
    href: "#",
    iconEmoji: "🔀",
    description: "Alternative solution 5",
    previewImage: "https://via.placeholder.com/600x400?text=Alternative+5",
  },
  {
    id: "alt-6",
    title: "Alternative 6",
    href: "#",
    iconEmoji: "🔀",
    description: "Alternative solution 6",
    previewImage: "https://via.placeholder.com/600x400?text=Alternative+6",
  },
  {
    id: "alt-7",
    title: "Alternative 7",
    href: "#",
    iconEmoji: "🔀",
    description: "Alternative solution 7",
    previewImage: "https://via.placeholder.com/600x400?text=Alternative+7",
  },
  {
    id: "alt-8",
    title: "Alternative 8",
    href: "#",
    iconEmoji: "🔀",
    description: "Alternative solution 8",
    previewImage: "https://via.placeholder.com/600x400?text=Alternative+8",
  },
];
