import { z } from "zod";

export const ProfileDataSchema = z.object({
  profilePhotoUrl: z.string().optional(),
  profileUrl: z.string(),
  fullName: z.string().optional(),
  headline: z.string().optional(),
  profileUrn: z.string().optional(),
});

export type ProfileData = z.infer<typeof ProfileDataSchema>;

export const ApifyLinkedInItemSchema = z.object({
  linkedinUrl: z.string().url().optional(),
  firstName: z.string().nullable().optional(),
  lastName: z.string().nullable().optional(),
  fullName: z.string().nullable().optional(),
  headline: z.string().nullable().optional(),
  connections: z.number().nullable().optional(),
  followers: z.number().nullable().optional(),
  email: z.string().nullable().optional(),
  mobileNumber: z.string().nullable().optional(),
  jobTitle: z.string().nullable().optional(),
  companyName: z.string().nullable().optional(),
  companyIndustry: z.string().nullable().optional(),
  companyWebsite: z.string().nullable().optional(),
  companyLinkedin: z.string().nullable().optional(),
  companyFoundedIn: z.number().nullable().optional(),
  companySize: z.string().nullable().optional(),
  currentJobDuration: z.string().nullable().optional(),
  currentJobDurationInYrs: z.number().nullable().optional(),
  topSkillsByEndorsements: z.string().nullable().optional(),
  addressCountryOnly: z.string().nullable().optional(),
  addressWithCountry: z.string().nullable().optional(),
  addressWithoutCountry: z.string().nullable().optional(),
  profilePic: z.string().nullable().optional(),
  profilePicHighQuality: z.string().nullable().optional(),
  about: z.string().nullable().optional(),
  publicIdentifier: z.string().nullable().optional(),
  openConnection: z.boolean().nullable().optional(),
  urn: z.string().nullable().optional(),
  experiences: z.unknown().optional(),
  updates: z.unknown().optional(),
  skills: z.unknown().optional(),
  profilePicAllDimensions: z.unknown().optional(),
  educations: z.unknown().optional(),
  licenseAndCertificates: z.unknown().optional(),
  honorsAndAwards: z.unknown().optional(),
  languages: z.unknown().optional(),
  volunteerAndAwards: z.unknown().optional(),
  verifications: z.unknown().optional(),
  promos: z.unknown().optional(),
  highlights: z.unknown().optional(),
  projects: z.unknown().optional(),
  publications: z.unknown().optional(),
  patents: z.unknown().optional(),
  courses: z.unknown().optional(),
  testScores: z.unknown().optional(),
  organizations: z.unknown().optional(),
  volunteerCauses: z.unknown().optional(),
  interests: z.unknown().optional(),
  recommendations: z.unknown().optional(),
});

export type ApifyLinkedInItem = z.infer<typeof ApifyLinkedInItemSchema>;
