import { z } from "zod";

// Make primitive types more restrictive for early validation
export const idSchema = z.string().min(1);
export const stringFieldSchema = z.string().min(1);
export const contentSchema = z.string().min(1);
export const urlSchema = z.string().url().optional().nullable();
export const cuidSchema = z.string().cuid();

export const createEntryInputSchema = z.object({
  content: z.string().min(1, { message: "Entry content cannot be empty." }),
});
export type CreateEntryInput = z.infer<typeof createEntryInputSchema>;

export const upvoteEntryInputSchema = z.object({
  entryId: z.string().cuid({ message: "Invalid entry ID format." }),
});
export type UpvoteEntryInput = z.infer<typeof upvoteEntryInputSchema>;

export const getPublicTimelineInputSchema = z.object({
  username: z.string().min(1, { message: "Username cannot be empty." }),
});
export type GetPublicTimelineInput = z.infer<
  typeof getPublicTimelineInputSchema
>;

export const storageStateSchema = z.object({
  scrollDuration: z.number(),
  commentDelay: z.number(),
  customStyleGuides: z.array(
    z.object({
      name: z.string(),
      prompt: z.string(),
    }),
  ),
  commentCount: z.number(),
  status: z.string(),
  maxPosts: z.number(),
  duplicateWindow: z.number(),
  styleGuide: z.string(),
  apiKey: z.string().optional(),
  commentAsCompanyEnabled: z.boolean(),
  timeFilterEnabled: z.boolean(),
  minPostAge: z.number(),
  finishListModeEnabled: z.boolean(),
  targetListEnabled: z.boolean(),
  totalTodayComments: z.number(),
  selectedTargetList: z.string(),
  commentProfileName: z.string(),
  languageAwareEnabled: z.boolean(),
  skipCompanyPagesEnabled: z.boolean(),
  skipPromotedPostsEnabled: z.boolean(),
  skipFriendsActivitiesEnabled: z.boolean(),
  blacklistEnabled: z.boolean(),
  targetListOptions: z.array(z.string()),
  blacklistAuthors: z.array(z.string()),
  manualApproveEnabled: z.boolean(),
  authenticityBoostEnabled: z.boolean(),
  profileRecord: z.record(
    z.string(),
    z.object({
      profileUrn: z.string().optional(),
      lists: z.array(z.string()).optional(),
    }),
  ),
  hasEverSignedIn: z.boolean(),
  totalAllTimeComments: z.number(),
  isRunning: z.boolean(),
  authorsFound: z.array(z.string()),
  authorsMissing: z.array(z.string()),
  authorsPending: z.array(z.string()),
  authorsCommented: z.array(z.string()),
  currentCommentCount: z.number(),
  postsSkippedDuplicate: z.number(),
  recentAuthorsDetected: z.number(),
  postsSkippedAlreadyCommented: z.number(),
  duplicatePostsDetected: z.number(),
  postsSkippedTimeFilter: z.number(),
  selectedStyleKey: z.string(),
});

export type StorageState = z.output<typeof storageStateSchema>;

export const countries = {
  AF: "Afghanistan",
  AL: "Albania",
  AD: "Andorra",
  AO: "Angola",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia and Herzegovina",
  BR: "Brazil",
  BG: "Bulgaria",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CI: "CoteDIvoire",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "CzechRepublic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  EC: "Ecuador",
  EG: "Egypt",
  EE: "Estonia",
  ET: "Ethiopia",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GR: "Greece",
  HT: "Haiti",
  HN: "Honduras",
  HK: "HongKong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KR: "Korea, Republic of",
  KW: "Kuwait",
  LV: "Latvia",
  LB: "Lebanon",
  LR: "Liberia",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MG: "Madagascar",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MR: "Mauritania",
  MU: "Mauritius",
  MX: "Mexico",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NL: "Netherlands",
  NZ: "New Zealand",
  NG: "Nigeria",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PA: "Panama",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RO: "Romania",
  RU: "Russian Federation",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  ZA: "South Africa",
  ES: "Spain",
  SD: "Sudan",
  SS: "South Sudan",
  SE: "Sweden",
  CH: "Switzerland",
  TW: "Taiwan",
  TH: "Thailand",
  TG: "Togo",
  TT: "Trinidad And Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VE: "Venezuela",
  VN: "Vietnam",
  VG: "Virgin Islands British",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
} as const;

export const countrySchema = z.enum(
  Object.keys(countries) as [
    keyof typeof countries,
    ...(keyof typeof countries)[],
  ],
);

export type CountrySchema = z.output<typeof countrySchema>;
