// DEPRECATED: This file is no longer used
// The AI comment generation has been moved to server-side tRPC API
// See: src/utils/ai-service.ts for the new implementation

/*
import { GoogleGenAI } from "@google/genai";

import type {
  CommentGeneratorConfig,
  CommentGeneratorError,
} from "./background-types";

/**
 * AI Comment Generator Service
 *
 * SERVICE CLASS - Handles AI comment generation
 * - Encapsulates Google GenAI integration and prompt engineering
 * - Manages error handling and fallback responses
 * - Provides clean interface for comment generation
 * - Centralizes AI-related logic separate from background script
 */

/*
export class AICommentGenerator {
  /**
   * Generate a comment using Google GenAI based on post content and configuration
   * @param postContent The LinkedIn post content to comment on
   * @param config API key and style guide configuration
   * @returns Promise resolving to generated comment string
   */
/*
  async generateComment(
    postContent: string,
    config: CommentGeneratorConfig,
  ): Promise<string> {
    console.log(
      "AICommentGenerator: Starting comment generation for content length:",
      postContent?.length || 0,
    );

    const ai = new GoogleGenAI({ apiKey: config.apiKey });

    const systemPrompt = `
  You are a LinkedIn influencer commenting on a post. 
  
  Generate concise but engaging comments for a single LinkedIn. 

  Super Importantly, ONLY REPSOND WITH THE COMMENT. DO NOT REPLY WITH ANYTHING ELSE LIKE QUOTATIONS OR ANYTHING ELSE.
  
  You must ahere to the style guide: ${config.styleGuide}. 
  
  Importantly, ahere strictly to the following additional rules:
  - Keep comments professional yet conversational
  - under 100 words
  - avoid generic responses.

  Super Importantly, ONLY REPSOND WITH THE COMMENT. DO NOT REPLY WITH ANYTHING ELSE LIKE QUOTATIONS OR ANYTHING ELSE.

  Generate a thoughtful comment for this LinkedIn post: ${postContent}

  Super Importantly, ONLY REPSOND WITH THE COMMENT. DO NOT REPLY WITH ANYTHING ELSE LIKE QUOTATIONS OR ANYTHING ELSE.

  Super Importantly, do not return any artefacts that might imply that the comment was generated by AI like placeholders [First's Name] or [Post Content].

  The postContent above likely starts with the author's name. Address the author's name somewhere in your comment. If you can't find a name, don't try to put in placeholder, just don't address them.

  It's important that you think very hard to make sure that what you return is as natural and human sounding/looking as possible without raising any red flags.

  `;

    try {
      const response = await ai.models.generateContent({
        model: "gemini-2.0-flash-lite",
        contents: systemPrompt,
        config: {
          maxOutputTokens: 100,
          temperature: 0.7,
        },
      });

      const generatedComment =
        response.text || "Great post! Thanks for sharing.";

      console.log(
        "AICommentGenerator: Successfully generated comment:",
        generatedComment.substring(0, 100) + "...",
      );
      return generatedComment;
    } catch (error) {
      const errorDetails: CommentGeneratorError = {
        message: error instanceof Error ? error.message : String(error),
        stack: error instanceof Error ? error.stack : undefined,
        name: error instanceof Error ? error.name : "Unknown",
        apiKey: config.apiKey ? "Present" : "Missing",
        styleGuide: config.styleGuide ? "Present" : "Missing",
        postContentLength: postContent ? postContent.length : 0,
        timestamp: new Date().toISOString(),
        type: "google_genai_error",
      };

      console.error(
        "AICommentGenerator: Error generating comment:",
        errorDetails,
      );

      // Send detailed error to content script via message
      try {
        chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
          if (tabs[0]?.id) {
            chrome.tabs.sendMessage(tabs[0].id, {
              action: "statusUpdate",
              error: errorDetails,
            });
          }
        });
      } catch (msgError) {
        console.error(
          "AICommentGenerator: Failed to send error message to content script:",
          msgError,
        );
      }

      // Re-throw the error so it can be caught by the promise handler
      throw error;
    }
  }
}
*/
